In [6]:
import numpy as np

from numpy import array

In [8]:
from numpy import array, float32, int64 

episode_dict = {'action': [array([0.0, 195.0, 185.0, 65.0, 0.0, 0.0]), 
                           array([0.0, 195.0, 185.0, 65.0, 0.0, 0.0]), 
                           array([0.0, 195.0, 185.0, 65.0, 0.0, 0.0]), 
                           array([0.0, 195.0, 185.0, 65.0, 0.0, 0.0]), 
                           array([0.0, 195.0, 185.0, 65.0, 0.0, 0.0])],
                'observation.state': [array([0.3515625, 187.64648, 176.57227, 66.00586, 0.26367188, 0.6060606 ], dtype=float32), 
                                      array([0.3515625, 187.64648, 176.57227, 66.00586, 0.26367188, 0.6060606 ], dtype=float32),
                                      array([0.3515625, 187.64648, 176.57227, 66.00586, 0.26367188, 0.6060606 ], dtype=float32), 
                                      array([0.3515625, 187.64648, 176.57227, 66.00586, 0.26367188, 0.6060606 ], dtype=float32), 
                                      array([0.3515625, 187.64648, 176.57227, 66.00586, 0.26367188, 0.6060606 ], dtype=float32)], 
                'timestamp': array([0.0, 0.03333334, 0.06666667, 0.1, 0.13333334], dtype=float32), 
                'frame_index': array([0, 1, 2, 3, 4], dtype=int64), 
                
                'episode_index': array([0, 0, 0, 0, 0]), 
                'index': array([0, 1, 2, 3, 4]), 
                'task_index': array([0, 0, 0, 0, 0])}

In [9]:
import datasets

In [ ]:
datasets.Dataset.from_dict(episode_dict, )

In [12]:
import pandas as pd

df = pd.read_parquet('C:/Users/DHoll/.cache/huggingface/lerobot/danielholl/test1/data/chunk-000/episode_000000.parquet', engine='pyarrow')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 658 entries, 0 to 657
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   timestamp      658 non-null    float32
 1   frame_index    658 non-null    int64
 2   episode_index  658 non-null    int64
 3   index          658 non-null    int64
 4   task_index     658 non-null    int64
dtypes: float32(1), int64(4)
memory usage: 23.3 KB
None

In [13]:
df.head(20)

    timestamp  frame_index  episode_index  index  task_index
0    0.000000            0              0      0           0
1    0.033333            1              0      1           0
2    0.066667            2              0      2           0
3    0.100000            3              0      3           0
4    0.133333            4              0      4           0
5    0.166667            5              0      5           0
6    0.200000            6              0      6           0
7    0.233333            7              0      7           0
8    0.266667            8              0      8           0
9    0.300000            9              0      9           0
10   0.333333           10              0     10           0
11   0.366667           11              0     11           0
12   0.400000           12              0     12           0
13   0.433333           13              0     13           0
14   0.466667           14              0     14           0
15   0.500000           15              0     15           0
16   0.533333           16              0     16           0
17   0.566667           17              0     17           0
18   0.600000           18              0     18           0
19   0.633333           19              0     19           0

In [15]:
df = pd.read_parquet('C:/Users/DHoll/Downloads/train-00000-of-00018.parquet', engine='pyarrow')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3750 entries, 0 to 3749
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   observation.state   3750 non-null   object
 1   observation.effort  3750 non-null   object
 2   action              3750 non-null   object
 3   episode_index       3750 non-null   int64
 4   frame_index         3750 non-null   int64
 5   timestamp           3750 non-null   float32
 6   next.done           3750 non-null   bool
 7   index               3750 non-null   int64
 8   task_index          3750 non-null   int64
dtypes: bool(1), float32(1), int64(4), object(3)
memory usage: 223.5+ KB
None

In [16]:
df.head()

,observation.state,observation.effort,action,episode_index,frame_index,timestamp,next.done,index,task_index
0,"[0.0, -0.96487397, 1.1673595, 0.0015339808, -0...","[-2.69, 88.770004, -223.27, 0.0, -180.23001, 0...","[0.013805827, -0.95567006, 1.1642915, 0.001533...",0,0,0.00,False,0,0
1,"[0.0, -0.96487397, 1.1688933, 0.0015339808, -0...","[-2.69, 88.770004, -225.96, -5.38, -180.23001,...","[0.013805827, -0.95567006, 1.1658255, 0.003067...",0,1,0.02,False,1,0
2,"[0.0015339808, -0.96487397, 1.1688933, 0.00153...","[72.630005, 199.06, -177.54001, 0.0, -43.04, -...","[0.012271847, -0.95567006, 1.1658255, 0.001533...",0,2,0.04,False,2,0
3,"[0.0015339808, -0.96487397, 1.1704273, 0.00153...","[48.420002, 215.20001, -193.68001, 0.0, -51.11...","[0.012271847, -0.95567006, 1.1658255, 0.001533...",0,3,0.06,False,3,0
4,"[0.0030679617, -0.96487397, 1.1704273, 0.00153...","[69.94, 217.89, -236.72, 0.0, -64.56, 18.83, 3...","[0.013805827, -0.95567006, 1.1658255, 0.001533...",0,4,0.08,False,4,0

In [20]:
from lerobot.common.datasets.lerobot_dataset import *

LeRobotDataset().features

TypeError: LeRobotDataset.__init__() missing 1 required positional argument: 'repo_id'